
name: deploy-ecr
run-name: Deploy ECR
inputs:
  image_name:
    description: The image name. Will be appended to namespace.
    required: true
    type: string
  image_tag:
    description: A tag value to set
    required: true
    type: string
  docker_folder:
    description: When building the action will step into this folder and run a docker build command.
    required: false 
    default: .
    type: string
  namespace:
    description: The namespace or prefix to use. Final image name will be a composite of this and the image name joined by a slash.
    required: true
    type: string
  ecr_account_id:
    description: The account id to push to. For internal use at jppol default value should be used.
    required: false
    type: string
    default: '354918371398'
  aws_region: 
    description: For internal use at jppol default value should be used.
    required: false
    type: string
    default: eu-west-1
  run_build:
    description: Set to false if you want to run the docker build your self. In this case the image must be tagged correctly as ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/NAMESPACE/IMAGE_NAME:IMAGE_TAG
    type: boolean
    default: true
  run_push:
    description: If set to false, nothing is pushed. If you need to tag your image correct given inputs, you can run this action but both run_build and run_push set to false and use the fully_qualified_name output to tag before using action again.
outputs:
  fully_qualified_name:
    value: ${{ steps.full_image_name.outputs.name }}

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.ecr_account_id }}:role/github-access-${{ inputs.namespace }}
        aws-region: ${{ inputs.aws_region }}
        role-skip-session-tagging: true

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registries: ${{ inputs.ecr_account_id }}
    - uses: int128/create-ecr-repository-action@v1
      id: ecr
      with:
        repository: ${{ inputs.namespace }}/${{ inputs.image_name }}
    - name: Create full image name
      id: full_image_name
      shell: bash
      run: |
        echo "name=${{ inputs.ecr_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ inputs.namespace  }}/${{ inputs.image_name }}:${{ inputs.image_tag }}" > $GITHUB_OUTPUT
        
    - name: Build image
      if: ${{ inputs.run_build }}
      id: build-image
      run: |
        cd ${{ inputs.docker_folder }}
        docker build . -t ${{ steps.full_image_name.outputs.name }}
    - name: Push image
      if: ${{ inputs.run_push }}
      id: push-image
      shell: bash
      env:
      run: |
        docker push ${{ steps.full_image_name.outputs.name }}
